on:
  push:
    branches:
      - master

jobs:
  web-deploy:

    name: 🚀 Deploy RollBot [DEV]
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 😎 Use Node.js v21
        uses: actions/setup-node@v3
        with:
          node-version: '21.2.0'
          cache: npm

    - name: 🧰 Install NPM Modules
      run: npm install

    - name: 🔨 Build Project
      run: npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_API_HOST }}
        username: ${{ secrets.FTP_API_USER }}
        password: ${{ secrets.FTP_API_PASSWORD }}
        local-dir: ./dist/
        server-dir: ${{ secrets.FTP_PROD_DIR }}
        dangerous-clean-slate: true
        protocol: ftp
