name: DEV Deploy

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js v21
        uses: actions/setup-node@v2
        with:
          node-version: '21.2.0'
          cache: npm

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

    #  - name: Copy package.json
    #    run: cp $GITHUB_WORKSPACE/package.json $GITHUB_WORKSPACE/dist/package.json

      - name: API Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_API_HOST }}
          username: ${{ secrets.FTP_API_USER }}
          password: ${{ secrets.FTP_API_PASSWORD }}
          server-dir: /public_nodejs/
          protocol: ftp
          local-dir: dist/

  restart-app:
    name: Restart
    runs-on: ubuntu-latest
    needs: build-and-deploy
    permissions:
      contents: write

    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd domains/${{ secrets.FTP_API_HOST }}/public_nodejs
            npm install
            mv main.js app.js
            devil www restart ${{ secrets.FTP_API_HOST }}
